### ISSUE TITLE
Is it possible to get a atom key map for a map property?

### ISSUE THREAD

**Issue by boon-wego** [martinthenth/goal#71]
For example:
```
use Goal

defparams :update do
  required(:translations, :map)
end

validate(:update, %{
  "translations" => %{"en" => %{"name" => "Foo"}}
})

# Returns
%{
  translations: %{en: %{name: "Foo"}}
}
```

Currently it returns
```
%{
  "translations" => %{"en" => %{"name" => "Foo"}}
}
```

**Comment by boon-wego** [comment]
Would be nice if the README have some docs on `properties`

**Comment by martinthenth** [comment]
Hi! Thanks for the issue, and I agree that the docs can mention why it doesn't build an atom-based map

The reason is that any external actor can send an unlimited list of unknown parameters, which would be translated into unlimited atoms. This exposes the client to a denial of service attack through atom exhaustion https://erlef.github.io/security-wg/secure_coding_and_deployment_hardening/atom_exhaustion.html

You can define predefined maps with Goal, with keys that you expect to receive, and those will be translated to atom-based maps since they are known to be safe (they atoms are already in the system). Any undefined map will translate to string-based maps since those are safe

Hope that helps 🙏🏻
