### ISSUE TITLE
Validate non-existing params

### ISSUE THREAD

**Issue by plammerts** [martinthenth/goal#77]
Hi! 

First of all, great library! Many thanks! 🙏🏻

I was wondering if there is (or will be) support for validating fields that do not occur in the `defparams`?

For example, suppose we have the following module:

```elixir
defmodule Params do
  use Goal

  defparams :body do
    optional :field, :string
  end
end
```

When I run the following, I get:
```
iex> Params.validate(:body, %{non_existing_field: "..."})
{:ok, %{}}
```

I would like to have the option to return an error tuple saying something like `:non_existing_field does not exist`.

Thanks in advance!

**Comment by martinthenth** [comment]
Hi! Thanks for your message. I think it is possible to add such a feature, but my question would be what you want to use it for? 

If your servers are exposed to the internet (untrusted traffic) then that feature could pose a security risk, because any external actor can send an unlimited list of parameters; which would accumulate memory (and maybe atoms, depending on the implementation) in the system. It could expose the servers to Denial of Service attacks through OOM and atom exhaustion https://erlef.github.io/security-wg/secure_coding_and_deployment_hardening/atom_exhaustion.html

For internal traffic it could be less harmful, if you know the client will receive only a few unknown parameters

**Comment by plammerts** [comment]
Thank you for your reply! I only needed it for internal use, but your response makes perfect sense. It's better not to include it then.

**Comment by srcrip** [comment]
I too am interested in this feature and I don't really get the issue, you can just choose to not dynamically create atoms for these errors. I understand goal does make atoms for the 'good' params, but it could just return error strings for any unallowed ones
